---
- hosts: localhost
  connection: local
  vars:
    docker_organization: wizdevops
  pre_tasks:
    - name: install docker-py
      become: true
      become_method: sudo
      pip: 
        name: docker-py
        state: present
  tasks:
    - name: grab the vcs-url
      command: git config --get remote.origin.url
      register: vcs_url

    - name: grab the vcs-ref
      command: git describe --long
      register: vcs_ref

    - name: build images and push to docker cloud
      docker_image:
        path: "{{ item.context }}"
        name: "{{ item.image }}"
        tag: "{{ item.tag }}"
        state: present
        force: true
        nocache: false
        push: true
        rm: true
        buildargs:
          BUILD_DATE: "{{ ansible_date_time.iso8601 }}"
          VERSION: "{{ item.version }}"
          VCS_URL: "{{ vcs_url.stdout }}"
          VCS_REF: "{{ vcs_ref.stdout }}"
      with_items:
        - { context: ./base_alpine,
            image: "{{ docker_organization }}/alpine",
            tag: latest,
            version: 1.0.2 }
        - { context: ./python/3,
            image: "{{ docker_organization }}/python",
            tag: 3-alpine,
            version: 1.1.0 }
        - { context: ./python/2.7,
            image: "{{ docker_organization }}/python",
            tag: 2.7-alpine,
            version: 1.1.1 }
        - { context: ./drupal/alpine,
            image: "{{ docker_organization }}/drupal",
            tag: 8-alpine,
            version: 1.3.0 }
        - { context: ./drupal/debian,
            image: "{{ docker_organization }}/drupal",
            tag: 8-debian,
            version: 1.1.0 }
        - { context: ./packer,
            image: "{{ docker_organization }}/packer",
            tag: latest,
            version: 0.11.0 }
        - { context: ./java,
            image: "{{ docker_organization }}/java",
            tag: 8-alpine,
            version: 1.1.0 }
        - { context: ./gocd/agent,
            image: "{{ docker_organization }}/gocdagent",
            tag: latest,
            version: 17.8.0-5277 }
        - { context: ./gocd/server,
            image: "{{ docker_organization }}/gocdserver",
            tag: latest,
            version: 17.8.0-5277 }
        - { context: ./monit,
            image: "{{ docker_organization }}/monit",
            tag: latest,
            version: 1.0.0 }
        - { context: ./golang,
            image: "{{ docker_organization }}/go",
            tag: latest,
            version: 1.7.3 }
        - { context: ./coffeescript,
            image: "{{ docker_organization }}/coffeescript",
            tag: latest,
            version: 1.1.0 }
        - { context: ./alpine-mysql,
            image: "{{ docker_organization }}/alpine-mysql",
            tag: latest,
            version: 1.0.0 }
        - { context: ./alpine-ansible,
            image: "{{ docker_organization }}/ansible",
            tag: latest,
            version: 1.1.0 }

